# 1. Origen: Carpeta donde la CajaApp guarda los archivos .dat e .idx
ruta_local=C:\\Proyecto_V1_arqui\\DATA

# 2. Destino: Ruta de red (Carpeta compartida SMB) del servidor central
ruta_red=\\\\LUIS\\Users\\luism\\Desktop\\DATOS

# 3. Frecuencia: Cada cuántos segundos el demonio revisará y copiará
intervalo_segundos=10